### ISSUE TITLE
Crash With Tadpole?

### ISSUE THREAD

**Issue by sherpascott** [Lemonszz/Biome-Makeover#210] opened 2023-04-08 10:21 UTC
Every now and then I get this weird crash about the game not being able to find the tadpole tail. Started after using entity model features with fresh animations, so that could be a culprit. Here's the crash. 
Please note it says crash caused by darkmode, but the only reason darkmode crashes is after the resources crashed, so it doesn't really have to do with it lol. The game doesn't close, but clicking on any button makes it shut down. 
[crash-2023-04-08_04.14.02-client.txt](https://github.com/Lemonszz/Biome-Makeover/files/11182986/crash-2023-04-08_04.14.02-client.txt)
[latest.log](https://github.com/Lemonszz/Biome-Makeover/files/11182987/latest.log)

**Comment by Lemonszz** [comment] 2023-04-12 09:56
This is an interesting issue that's not really anyone's fault (except maybe optifine's).   

My Theory:  
The issue is that optifine's model format (CEM) is looking for any entity with the name "tadpole"  instead of something like `minecraft:tadpole`.  

So we have our legacy tadpole entity, with the id `biomemakeover:tadpole`, optifine's animation system is then looking for a part named "tail" on our tadpoles model... and can't find one = crash. 

This is all just a guess, I'm not familiar with CEM to say this is the issue for sure, but we're not aiming for Optifine compatibility for various reasons, so I'm going to close this issue.

Sorry I couldn't be of further help.

**Closed as completed by Lemonszz** 2023-04-12 09:56 UTC

**Comment by sherpascott** [comment] 2023-04-13 02:52
All good thx for the help! I haven't had the issue again and I'm not sure why, just kinda fixed itself.
