### ISSUE TITLE
Stone golems don't despawn properly when killed

### ISSUE THREAD

**Issue by Warhand** [Lemonszz/Biome-Makeover#158] opened 2022-09-05 05:59 UTC
Was in a testing world recently and killed a stone golem, and at first I thought nothing was wrong, but Jade (Waila fork) reported the stone golem was still there in the spot where it had just been killed, and I could still stand in the spot where it used to be and collide with its hitbox. However when using the shown hitboxes keybind, it showed there was nothing there, even though I could stand on top of the spot where Jade said a stone golem was.

Unsure of the cause of this, I tried killing a golem that both had and didn't have a crossbow, and I tried killing a golem with and without instakill on, the issue persisted in all events.

Biome makeover version: 1.4.31

![2022-09-05_01 49 23](https://user-images.githubusercontent.com/29134223/188370557-4187d01f-0442-43a7-bc8e-a997b8cf7d24.png)
![2022-09-05_01 49 31](https://user-images.githubusercontent.com/29134223/188370559-3600f9c8-12b8-43f5-8b36-ced62cc124f2.png)

**Comment by Lemonszz** [comment] 2022-09-05 06:04
Yeah, it's a known issue I've never gotten around to fixing.

Luckily it's only client-sided, so reloading the world or loading/unloading the chunks should make it disappear.

**Comment by Lemonszz** [comment] 2022-11-10 21:31
Oops I should have closed this as a duplicate of #119, thanks for reporting though.

**Closed as completed by Lemonszz** 2022-11-10 21:31 UTC
