### ISSUE TITLE
Server Timeout on loading Mansion

### ISSUE THREAD

**Issue by Nydid** [Lemonszz/Biome-Makeover#74] opened 2022-02-01 08:06 UTC
Anytime the player loads the mansion, the server times out.

Biome Makeover v1.4.3
https://pastebin.com/6Nz2N4Tn

**Comment by Lemonszz** [comment] 2022-02-02 19:21
Can't seem to recreate this on my end,

If you have a latest.log file to go along with the timeout crash report that may help a lot.

**Comment by Nydid** [comment] 2022-02-05 15:01
Here's the latest.log

https://pastebin.com/WXw601Az

**Comment by Monster-Zer0** [comment] 2022-03-03 14:45
getting something similar but with tumbleweeds


https://aofpaste.com/goqoqugayu.yaml
https://spark.lucko.me/eiMoOx3DuB

spawning inside unloaded chunks perhaps?

same as https://github.com/Lemonszz/Biome-Makeover/issues/36

**Comment by Kierecko** [comment] 2022-03-03 16:19
I'm running into the same issue.

https://pastebin.com/N9Vr6Z5v

**Comment by Lemonszz** [comment] 2022-03-03 17:54
y'all should update to the latest version.

@Monster-Zer0 not sure where you're getting tumbleweeds from, but it looks like it may be an issue with mesmerite boulder gen.

@Kierecko nothing in there particularly points towards BM, but I'm not ruling it out. Do you know if a mansion was generating at the time?

**Comment by Monster-Zer0** [comment] 2022-03-03 18:31
![image](https://user-images.githubusercontent.com/5826746/156629205-a1ddf0ed-86ab-43b7-a78f-f738f90bce88.png)
this is where I am getting tumbleweeds from

**Comment by Kierecko** [comment] 2022-03-03 20:53
@Lemonszz It must have been, yes. The first time I used the locate command and teleported there and the second I flew there. Half the mansion was generated by the time I flew closer and then the server crashed. Luckily it's on a testing server where we check for mod compatibilities rn. But I'll check for the version for sure!

Edit: I just put the latest version in and the issue is still there.

**Comment by dandin87** [comment] 2022-03-17 04:46
> y'all should update to the latest version.
> 
> @Monster-Zer0 not sure where you're getting tumbleweeds from, but it looks like it may be an issue with mesmerite boulder gen.
> 
> @Kierecko nothing in there particularly points towards BM, but I'm not ruling it out. Do you know if a mansion was generating at the time?

So we have been getting this crash somewhat often on one of the All of Fabric 5 servers, Specifically the server that we did not pregren, and then i ran across this issue. So I went ahead and did
/locate biomemakeover:mansion  
/tp 
then server dies.

Biome Makeover 1.18.1-1.4.8 (latest 1.18.1 version)
https://aofpaste.com/xijoqoqeri.yaml

**Comment by Lemonszz** [comment] 2022-03-17 06:00
This is an annoying issue, I've never been able to recreate it on my end, so there's some level of randomness to it.

If someone can work out exactly what's wrong that would be great.

**Comment by dandin87** [comment] 2022-03-17 18:41
> This is an annoying issue, I've never been able to recreate it on my end, so there's some level of randomness to it.
> 
> If someone can work out exactly what's wrong that would be great.

Here is some info from a dev looking at the crash log. Hopefully it is helpful to you.

Wesley1808 — 03/07/2022
Looks me to as if some mod is calling world.getChunk() from another thread causing constant sync loads (like 99% of other watchdog crashes)
Whatever mod that may be, no clue. It would help if they didn't call it asynchronously for no reason, since that piece of code will always be forced to run on the main thread anyway.
It only makes it more difficult for users to find out what is causing the issue.

**Comment by dandin87** [comment] 2022-03-27 19:49
To add to this, it appears that adding C2ME makes it not crash. For AoF5 since we are still on 1.18.1 that would be this version
https://github.com/RelativityMC/C2ME-fabric/suites/5372194438/artifacts/168579432

**Comment by YnwLNE** [comment] 2022-03-28 02:50
Having this issue too, tested in several worlds with and without the mod (some with vanilla mansions then adding in biome makeover mansions + vice versa) and within a 400-800 block radius of the mansion it times out any players nearby, trapping them as online until the server restarts. I'm personally running my own modpack via server provider Pebblehost with the premium option with the following specs: Intel i9-9900K / Xeon E-2236 @ 4.8Ghz, 7168 MBs DDR4 2666MHz Memory. Maybe this happens under certain heavy mod loads but I haven't been able to not reproduce it.

Latest fabric and 1.18.1

**Comment by Lemonszz** [comment] 2022-03-28 03:06
Has anyone managed to recreate this with JUST Biome Makeover (+ FAPI, Arch)

Also is everybody who has experience this running on a server? If so, do they generate correctly in singleplayer?

Providing mod lists may also help, to see if we can track down any common element that may be the issue.

**Comment by YnwLNE** [comment] 2022-03-28 14:15
here's my modpacks modlist: https://pastebin.com/KaRgBQtW but i have had it occur (although randomly) with it nearly or completely standalone

**Comment by 3HoursLater** [comment] 2022-03-28 22:31
I'm having this issue in my server too. 1.18.1, All of Fabric 5, v.1.1.1
Tried a different single player world, all fine.

**Comment by Lemonszz** [comment] 2022-04-01 08:28
I *believe* I've fixed this as of 1.14.17. 
Thanks for your reports and information everybody.

So I'll close this issue, feel free to comment if it reappears.

**Closed as completed by Lemonszz** 2022-04-01 08:28 UTC
Labels: help wanted, Information Wanted
